export const things = [
    {
        name: 'book',
        canHold: true,
        // heldBy: null,
        canUse: true,
        description: 'The book is brown with a golden imprint. It\'s rather tattered looking.', 
        position: 'b1',
        situation: 'on'
        // isLocked: false,
        // useCount: useCount,
        // useLimit: ,
        // consumable: consumable,
        // hasRequirement: hasRequirement,
        // requirement: requirement,
    },
    {
        name: 'key',
        canHold: true,
        // heldBy: null,
        canUse: true,
        description: 'The key is heavy. Looks pretty old as well. There\'s an inscription reading "With love".', 
        position: 'b2',
        situation: 'on'
        // isLocked: false,
        // useCount: useCount,
        // useLimit: ,
        // consumable: consumable,
        // hasRequirement: hasRequirement,
        // requirement: requirement,
    },
    {
        name: 'beer can',
        canHold: true,
        // heldBy: null,
        canUse: true,
        description: 'Coors. Empty and slightly dented. There is red lipstick along it\'s rim', 
        position: 'c2',
        situation: 'on'
        // isLocked: false,
        // useCount: useCount,
        // useLimit: ,
        // consumable: consumable,
        // hasRequirement: hasRequirement,
        // requirement: requirement,
    },
    {
        name: 'underwire bra',
        canHold: true,
        // heldBy: null,
        canUse: true,
        description: 'A lacey undergarment. Large enough to wear as a Roman war helmet.', 
        position: 'c2',
        situation: 'on'
        // isLocked: false,
        // useCount: useCount,
        // useLimit: ,
        // consumable: consumable,
        // hasRequirement: hasRequirement,
        // requirement: requirement,
    },
    {
        name: 'metal door',
        canHold: true,
        // heldBy: null,
        canUse: true,
        description: 'The door looks like it would withstand nuclear testing. It\' gray and scratched. There\'s a key hole under the rusty handle.', 
        position: 'c3',
        situation: 'fixed',
        isLocked: true,
        // useCount: useCount,
        // useLimit: ,
        // consumable: consumable,
        hasRequirement: true,
        requirement: 'key',
    }
];